//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Url
    {
        public int i_UrlId { get; set; }
        public string c_UrlTitle { get; set; }
        public string c_Url { get; set; }
        public string c_UrlDesc { get; set; }
        public Nullable<int> i_CategoryId { get; set; }
        public Nullable<int> i_UserId { get; set; }
        public string c_IsApproved { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
